### PR TITLE
Feature/v1-256 | Controllers structure refactored

### PR DESCRIPTION
**Pull request by dapodev**
# Changes

Changed controller structure, import/export rules according to [ticket](https://trello.com/c/gek5yTH9/263-v1-256-controllers-structure).

### CODE REVIEW

**Review by SaXaPhonist — APPROVED** [review]

**Comment by SaXaPhonist** [comment]
Did you check it with tests?

**Comment by SaXaPhonist** [comment]
please, write  3+ tests for new utils and functions

**Comment by dapodev** [comment]
> Did you check it with tests?

Could you pls provide instruction about how to run controllers' tests?

**Comment by dapodev** [comment]
> please, write 3+ tests for new utils and functions

done. Described tests for new utils

**Review by SaXaPhonist — APPROVED** [review]

**Pull request merged**
