### PR TITLE
Bug-fix/ 148 - myCourses pagination

### PR DESCRIPTION
**Pull request by SaXaPhonist**
- add additional ref for myCourses

### CODE REVIEW

**Review by irina-sinitsyna — DISMISSED** [review]

**Review by irina-sinitsyna — CHANGES_REQUESTED** [review]
Please remove all the comments

**Review by dapodev — COMMENTED** [review]
Not working on my machine 😢

**Review by dapodev — COMMENTED** [review]
Oops, my bad. Everything is fine 😄. But I don't get the purpose of `Numbers` enum.

**Comment by SaXaPhonist** [comment]
> 

@dapodev  to replace all single magic numbers

**Review by k-krasilnikova — APPROVED** [review]

**Pull request merged**
